# This document is requirement of Helm Chart.
# Reference:
#   https://helm.sh/docs/developing_charts/#templates-and-values

ingress:
  host: "edelweiss.rushhourgame.net"
  tls:
    crt: |-
      -----BEGIN CERTIFICATE-----
      -----END CERTIFICATE-----
    key: |-
      -----BEGIN PRIVATE KEY-----
      -----END PRIVATE KEY-----
  # max image size for docker registry
  proxy-body-size: "512m"

persistence:
  enabled: false
  storageClass: ""
  size: "4Gi"