apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "registry.name" . | quote }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "registry.name" . | quote }}
  template:
    metadata:
      labels:
        app: {{ include "registry.name" . | quote }}
    spec:
      containers:
        - name: registry
          image: registry:2
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: data
              mountPath: /var/lib/registry/
              subPath: registry
      volumes:
        - name: data
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim: 
            claimName: {{ include "storage.claim.name" . | quote }}
        {{- else }}
          emptyDir: {}
        {{- end -}}