{{/* 初回インストール時はRegistryが存在しない。Registry構築後に有効化する */}}
{{- if .Release.IsUpgrade }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.name" . | quote }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "app.name" . | quote }}
  template:
    metadata:
      labels:
        app: {{ include "app.name" . | quote }}
      annotations:
        timestamp: {{ date "2006/01/02T15:04:05" .Release.Time | quote }}
    spec:
      containers:
        - name: edelweiss
          image: {{ .Values.ingress.host }}/edelweiss:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: data
              mountPath: /var/www/html/public/storage
              subPath: edelweiss/storage
      volumes:
        - name: data
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim: 
            claimName: {{ include "storage.claim.name" . | quote }}
        {{- else }}
          emptyDir: {}
        {{- end -}}
{{- end -}}