apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name | quote }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name | quote }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name | quote }}
    spec:
      containers:
        - name: registry
          image: registry:2
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: data
              mountPath: /var/lib/registry/
              subPath: registry
      {{/* 初回インストール時はRegistryが存在しない。Registry構築後に有効化する */}}
      {{- if .Release.IsUpgrade }}
        - name: edelweiss
          image: {{ .Values.ingress.host }}/edelweiss:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: data
              mountPath: /var/www/html/public/storage
              subPath: edelweiss/storage
      {{- end }}
      volumes:
        - name: data
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim: 
            claimName: {{ .Release.Name }}-storage-claim
        {{- else }}
          emptyDir: {}
        {{- end -}}