apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name | quote }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: {{ .Values.ingress.proxy-body-size | quote }}
spec:
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths: 
          - path: /v2/
            backend:
              serviceName: {{ .Release.Name | quote }}
              servicePort: 5000
  tls:
    - hosts:
        - {{ .Values.ingress.host | quote }}
      secretName: {{ .Release.Name }}-tls