{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-storage-claim
  namespace: {{ .Release.Namespace | quote }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistence.storageClass | quote }}
  storageClassName: {{ .Values.persistence.size | quote }}
{{- end -}}