apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ include "tls.name" . | quote }}
  namespace: {{ .Release.Namespace | quote }}
data:
  tls.crt: |
    {{ .Values.ingress.tls.crt | b64enc }}
  tls.key: |
    {{ .Values.ingress.tls.key | b64enc }}