apiVersion: v1
kind: Service
metadata:
  name: {{ include "registry.name" . | quote }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "registry.name" . | quote }}
  ports:
    - name: {{ include "registry.name" . | quote }}
      port: 5000