apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name | quote }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name | quote }}
  ports:
    - name: {{ .Release.Name }}-registry
      port: 5000